config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks" }
  get "/books/most_recent_book", to: "books#most_recent_book"
  resources :books do
    resources :comments, only: [:index, :new, :edit, :show]
  end

  resources :comments

  get "/search", to: "search#results"
  
  
  root to: "home#page"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :book

    validates :content, presence: true
    validates :user_id, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_comment, only: [:update, :destroy, :show, :edit]
    def index
        if current_user
            if params[:book_id]
                @book = Book.find_by(id: params[:book_id])
                if @book.nil?
                    flash[:alert] = "Book not found"
                    redirect_to books_path
                else
                @comments = @book.comments
                end
            else
                @comments = Comment.all
            end
        else
            flash[:notice] = "Please sign up or sign"
            redirect_to "/"
        end
    end

    def new
        if current_user
            if params[:book_id] && !Book.exists?(params[:book_id])
                flash[:alert] = "Book not found"
                redirect_to books_path
            else
                @comment = Comment.new(book_id: params[:book_id], user_id: current_user.id)
            end
        else
            flash[:notice] = "Please sign up or sign"
            redirect_to "/"
        end
    end

    def create
        @comment = Comment.create(comments_params)
        if @comment.save
            flash[:success] = "Comment created successfully"
            redirect_to book_path(@comment.book)
        else
            flash[:alert] = @comment.errors
            render "new"
        end

    end

    def update
        if @comment.user_id == current_user.id || current_user.admin
            @comment.update(comments_params)
            if @comment.save
                flash[:success] = "Comment updated"
                redirect_to @comment
            else
                flash[:alert] = @comment.errors
                render :edit
            end
        else
            flash[:alert] = "Cannot edit other users comments"
            redirect_to "/"
        end

    end

    def edit
        if current_user
            if params[:book_id]
                book = Book.find_by(id: params[:book_id])
                if book.nil?
                    flash[:alert] = "Book not found"
                    redirect_to books_paths
                else
                flash[:alert] = "Comment not found" if @comment.nil?
                redirect_to book_comments_path(book)
                end
            else
                redir_if_not_found(@comment)
            end
        else
            flash[:notice] = "Please sign up or sign"
            redirect_to "/"
        end
    end

    def destroy
        if @comment.user_id == current_user.id || current_user.admin
            @comment.destroy
            flash[:success] = "Successfully deleted comment"
            redirect_to "/"
        else
            flash[:alert] = "Cannot delete other people's comments"
            redirect_to book_path(@comment.book)
        end
    end

    def show
        if current_user
            if params[:book_id]
                @book = Book.find_by(id: params[:book_id])
                if @comment.nil?
                    flash[:alert] = "Comment not found"
                    redirect_to book_comments_path(@book)
                end
            else
                redir_if_not_found(@comment)
            end
        else
            flash[:notice] = "Please sign up or sign"
            redirect_to "/"
        end
    end
    
    private

    def comments_params
        params.require(:comment).permit(:content, :user_id, :book_id)
    end

    def set_comment
        @comment = Comment.find_by_id(params[:id])
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for @comment do |f| %>

<% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2>There were some errors:</h2>
      <ul>
        <% @comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="jumbotron">
  <div class="field">
    <%= f.label :content %> <br />
    <%= f.text_area :content, cols: 25, rows: 10%>
  </div>

  <div class="field">
    <%= f.label :user %> <br />
    <%= f.text_field :user_id, {readonly: true}%>
  </div>

  <div class="field">
    <%= f.label :book %> <br />
    <%= f.text_field :book_id, {readonly: true}%>
  </div>

  <div class="actions">
    <%= f.submit%>
  </div>
</div>
<% end %>

app/views/comments/_list.html.erb
<%if current_user.admin%>
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <table class="table table-striped table-bordered">
            <thead>
                <th>Email</th>
                <th>Comment </th>
                <th>Time </th>
                <th>Admin </th>
            </thead>
            <tbody>
                <% user_comments.each do |comment| %>
                <tr>
                    <td><%=comment.user.email%></td>
                    <td><%=comment.content%></td>
                    <td><%=comment.created_at %></td>
                    <td><%=link_to "Delete", comment_path(comment), method: :delete, data: { confirm: 'Are you certain you want to delete this?' }%> / 
                    <%= link_to "Edit", edit_comment_path(comment) %></td>
                </tr>
                <%end%>
            </tbody>
            </table>
        </div>
    </div>
</div>
<%else%>
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <table class="table table-striped table-bordered">
            <thead>
                <th>Email</th>
                <th>Comment </th>
                <th>Time </th>
                <th>Admin </th>
            </thead>
            <tbody>
                <% user_comments.each do |comment| %>
                <tr>
                    <td><%=comment.user.email%></td>
                    <td><%=link_to comment.content, comment_path(comment)%></td>
                    <td><%=comment.created_at %></td>
                    <%if current_user.id == comment.user_id%>
                    <td><%=link_to "Delete", comment_path(comment), method: :delete, data: { confirm: 'Are you certain you want to delete this?' }%> / 
                    <%= link_to "Edit", edit_comment_path(comment) %></td>
                    <%end%>
                </tr>
                <%end%>
            </tbody>
            </table>
        </div>
    </div>
</div>
<%end%>

app/views/comments/edit.html.erb
<br>
<h2> Edit Comment</h2>
<br>

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <%= render "form" %>
        </div>
    </div>
</div>

app/views/comments/index.html.erb
<br>
<h1> All Comments </h1>
<br>
<%= render partial: "list", locals: {user_comments: @comments}%>

app/views/comments/new.html.erb
<br>
<h2> New comment </h2>
<br>

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <%= render "form" %>
        </div>
    </div>
</div>

app/views/comments/show.html.erb
<br>
<h1> Comment </h1>
<br>
<div class="jumbotron">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
            <%=@comment.content%>
            <br>
            <br>
            <%=@comment.created_at%>
            <br>
            <%= link_to "Home", "/"%>
            <%if current_user.id == @comment.user_id || current_user.admin%>
            <br>
                <%= link_to "Edit comment", edit_comment_path(@comment)%>
            <%end%>
            <br>
            <%= link_to "What's happening in the conversation?", book_path(@comment.book)%>
            <br>
            </div>
        </div>
    </div>
</div>