config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks" }
  get "/books/most_recent_book", to: "books#most_recent_book"
  resources :books do
    resources :comments, only: [:index, :new, :edit, :show]
  end

  resources :comments

  get "/search", to: "search#results"
  
  
  root to: "home#page"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    def results
        if current_user
            search_results = Book.search_books(params["search"]["query"])
            @books = search_results["items"]
        else
            flash[:notice] = "Please sign up or sign in to search for books"
            redirect_to "/"
        end
        
    end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/results.html.erb
<br>
<h2> Search Results </h2>
<br>

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <table class="table table-striped table-bordered">
            <thead>
                <th>Title </th>
                <th>Author </th>
                <th>Add to Library </th>
                <th>Read Book </th>
            </thead>
            <tbody>
                <%@books.each do |book|%>
                <tr>
                    <td><%=book["volumeInfo"]["title"]%></td>
                    <td><%=book["volumeInfo"]["authors"].to_a[0]%></td>
                    <td><%=link_to book["volumeInfo"]["title"], new_book_path(book)%></td>
                    <td><%=link_to "Go to Google Books", book["volumeInfo"]["previewLink"], target: :_blank %></td>
                </tr>
                <%end%>
            </tbody>
            </table>
        </div>
    </div>
</div>