config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks" }
  get "/books/most_recent_book", to: "books#most_recent_book"
  resources :books do
    resources :comments, only: [:index, :new, :edit, :show]
  end

  resources :comments

  get "/search", to: "search#results"
  
  
  root to: "home#page"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord

    has_many :comments
    has_many :users, through: :comments

    validates :title, presence: true
    validates :self_link,{ presence: true, uniqueness: true}
    validates :author, presence: true
    validates :preview_link, presence: true


#     "selfLink": "https://www.googleapis.com/books/v1/volumes/yHZhswEACAAJ",
#    "volumeInfo": {
#     "title": "Health, Safety and Environment Test",
#     "subtitle": "For Operatives and Specialists",
#     "authors": [
#      "Construction Industry Training Board (2013- )"

# imageLinks": {
#      "smallThumbnail": "http://books.google.com/books/content?id=yHZhswEACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api",
#      "thumbnail": "http://books.google.com/books/content?id=yHZhswEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api"

# "previewLink": "http://books.google.co.uk/books?id=yHZhswEACAAJ&dq=test&hl=&cd=1&source=gbs_api",

    def self.search_books(query_string, author="", title="") 
        url = "https://www.googleapis.com/books/v1/volumes?q=#{query_string.to_s}&maxResults=15&key=#{ENV["API_KEY"]}"

        response = HTTParty.get(url)
        results = response.parsed_response
        results
    end

    def self.get_book(self_link)
       response = HTTParty.get(self_link)
       result = response.parsed_response
       result
    end

    def self.most_recent_book
        all.last
    end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :set_book, only: [:update, :destroy, :show, :edit]
    def index
        if current_user
            if current_user.admin
                @books = Book.all
            else
                flash[:notice] = "Only admins can be here"
                redirect_to "/"
            end
        else
            flash[:notice] = "Please sign up or sign"
            redirect_to "/"
        end
    end

    def new
        if current_user
            @book = current_user.books.new
            @book.title = params["volumeInfo"]["title"]
            @book.author = params["volumeInfo"]["authors"].first
            @book.self_link = params["selfLink"]
            @book.preview_link = params["volumeInfo"]["previewLink"]
        else
            flash[:notice] = "Please sign up or sign"
            redirect_to "/"
        end
    end

    def create
        @book = current_user.books.create(book_params)
        if @book.save
            flash[:success] = "Book added to library successfully."
            redirect_to book_path(@book)
        else
            @book = Book.find_by(self_link: params[:book][:self_link])
            flash[:warning] = "A user already has this book in their library."
            @book.users.ids << current_user.id
            redirect_to book_path(@book)
        end
    end

    def edit
        if current_user
            redir_if_not_found(@book)
        else
            flash[:notice] = "Please sign up or sign"
            redirect_to "/"
        end
    end

    def update
        @book.update(book_params)
        @book.save
        flash[:success] = "Successfully updated book"
        redirect_to book_path(@book)
    end

    def destroy
        @book.comments.destroy_all
        @book.destroy
        flash[:success] = "Successfully deleted book"
        redirect_to "/"
    end

    def show
        if current_user
            redir_if_not_found(@book)
        else
            flash[:notice] = "Please sign up or sign"
            redirect_to "/"
        end
    end

    def most_recent_book
        @book = Book.most_recent_book
        render :show
    end


    private

    def book_params
        params.require(:book).permit(:id, :title, :author, :self_link, :preview_link)
    end

    def set_book
        @book = Book.find_by_id(params[:id])
    end


end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<% if current_user.admin %>
<%= form_for @book do |f| %>

<% if @book.errors.any? %>
    <div id="error_explanation">
      <h2>There were some errors:</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title%>
  </div>

  <div class="field">
    <%= f.label :author %> <br />
    <%= f.text_field :author%>
  </div>

  <div class="field">
    <%= f.label :self_link %><br />
    <%= f.text_field :self_link, :readonly => true%>
  </div>
  
  <div class="field">
    <%= f.label :preview_link %><br />
    <%= f.text_field :preview_link, :readonly => true %>
  </div>

  <div class="actions">
    <%= f.submit%>
  </div>
<% end %>
<%else%>
<%= form_for @book do |f| %>

<% if @book.errors.any? %>
    <div id="error_explanation">
      <h2>There were some errors:</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, :readonly => true%>
  </div>

  <div class="field">
    <%= f.label :author %> <br />
    <%= f.text_field :author, :readonly => true%>
  </div>

  <div class="field">
    <%= f.label :self_link %><br />
    <%= f.text_field :self_link, :readonly => true%>
  </div>
  
  <div class="field">
    <%= f.label :preview_link %><br />
    <%= f.text_field :preview_link, :readonly => true %>
  </div>

  <div class="actions">
    <%= f.submit%>
  </div>
<% end %>
<%end%>

app/views/books/_list.html.erb
<br>
<h2> My Library </h2>
<br>
<%if current_user.admin %>
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <table class="table table-striped table-bordered">
            <thead>
                <th>Title </th>
                <th>Author </th>
                <th>Read Book </th>
                <th>Admin </th>
            </thead>
            <tbody>
                <%user_books.each do |book|%>
                <tr>
                    <td><%= link_to book.title, book_path(book)%></td>
                    <td><%=book.author%></td>
                    <td><%=link_to "Go to Google Books", book.preview_link, target: :_blank %></td>
                    <td><%=link_to "Delete", book_path(book), method: :delete, data: { confirm: 'Are you certain you want to delete this?' }%> / 
                    <%= link_to "Edit", edit_book_path(book)%></td>
                </tr>
                <%end%>
            </tbody>
            </table>
        </div>
    </div>
</div>

<%else%>

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <table class="table table-striped table-bordered">
            <thead>
                <th>Title </th>
                <th>Author </th>
                <th>Read Book </th>
            </thead>
            <tbody>
                <%user_books.each do |book|%>
                <tr>
                    <td><%= link_to book.title, book_path(book)%></td>
                    <td><%=book.author%></td>
                    <td><%=link_to "Go to Google Books", book.preview_link, target: :_blank %></td>
                </tr>
                <%end%>
            </tbody>
            </table>
        </div>
    </div>
</div>

<%end%>

app/views/books/edit.html.erb
<br>
<h2> Edit Book </h2>
<br>

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <%= render "form" %>
        </div>
    </div>
</div>

app/views/books/index.html.erb
<br>
<h1> All Books </h1>
<br>
<%= render partial: "list", locals: {user_books: @books} %>

app/views/books/show.html.erb
<br>
<h1><%=@book.title%></h1>
<br>
<h2><%=@book.author%></h2>
<%=link_to "Read Book", @book.preview_link, target: :_blank%>
<br>
<%= link_to "add comment", new_book_comment_path(@book)%>
<br>
<%=render partial: "comments/list", locals: {user_comments: @book.comments} %>